Update SynthTime

diff --git a/SynthTime b/SynthTime
--- a/SynthTime
+++ b/SynthTime
@@ -1,1 +1,58 @@
 
+#!/bin/tcsh -f
+echo " "
+echo " "
+echo "     *******************************************************************"
+echo "     ==================================================================="
+echo "     =======================    SYNTH TIME   ==========================="
+echo "     ================ RTL to Timing Flow Automation Tool ==============="
+echo "     ==================================================================="
+echo "     ==================================================================="
+echo "     *******************************************************************"
+
+echo "       "
+echo "    This tool takes RTL netlist & SDC constraints as input and generates"
+echo "       a synthesized netlist and pre-layout timing report as output."
+echo "                                                                    "
+echo "                              It integrates:"
+echo "                         • Yosys  - for synthesis"
+echo "                 • OpenTimer - for static timing analysis"
+echo "                   "
+echo "                Developed and Maintained by: G R Shivaranjani"
+echo "              Acknowledgement: Kunal Ghosh, vlsisystemdesign.com"
+echo " "
+echo " "
+
+
+set my_work_dir = 'pwd'  
+#---------------------------------------------------------#
+#-----------Tool Initialization---------------------------#
+#---------------------------------------------------------#
+
+  
+ if ($#argv != 1) then
+	   echo "Info : Please Provide the csv file"
+	   exit 1
+ endif
+
+if (! -f $argv[1] || $argv[1] == "-help") then
+	if ($argv[1] == "-help") then
+		echo USAGE: ./SynthTime \<csv file\>
+		echo
+		echo 		where \<csv file\> consists of 2 columns
+		echo
+		echo           	\<Design Name\> is the name of top level module 
+		echo
+		echo            \<Output Directory\> is the name of Output Directory where you want to dump synthesis script, synthesized netlist and timing reports
+		echo 
+		echo             \<Early Libary Path\> is the file path of the early cell libary to be used for STA
+		echo
+                echo             \<Late Libary Path\> is the file path of the late cell libary to be used for STA
+		echo
+                echo             \<Constraints file\> is the file path of constraints to be used for STA
+	else 
+		echo "ERROR: Cannot find the CSV file $argv[1]. Exiting"
+	endif
+else
+		tclsh SynthTime.tcl  $argv[1]
+endif
